### ISSUE TITLE
How to compute direction of the moving object from motion energy features?

### ISSUE THREAD

**Issue by Sino0904** [gallantlab/pymoten#25]
Hello,

This is the first time I am using this library and learning about motion energy as a topic, so I would like to apologize for the very naive question.  I would like to use this library to compute direction of motion for a moving object in a given video. Can you tell me to do it using this library?

Thanks a lot

**Comment by anwarnunez** [comment]
Hi! 
It sounds like you need software to detect an object and then track its direction of motion. Unfortunately, pymoten might not be the best library to achieve your goal. pymoten does not provide object tracking; it computes how much motion there is in a fixed number of directions and within a fixed location of the video. So if you were to draw a box around the object you wish to track and then create a video of that, then pymoten would do what you want. Hope that helps!
